version : "3"
services:
  # quarkus:
  #   build:
  #     context: .
  #   ports:
  #     - 8082:8082
  #   networks:
  #     - default
  #     - monitor-net
  #   depends_on:
  #     - jaeger
  #     - db
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  jaeger:
    image: jaegertracing/all-in-one
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 9411:9411

networks:
  monitor-net:
    external:
      name: dockprom_monitor-net